# Reference: https://www.tomray.dev/nestjs-docker-compose-postgres

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    env_file:
    - .config/development.env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - 3000:3000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Optional: Expose Redis on localhost for external access
    command: redis-server --save "" --appendonly no  # Disables persistence features

  test:
    build:
      dockerfile: Dockerfile
      context: .
      # Build the same development stage
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .config/development.env
    command: npm run test